apiVersion: v1
kind: Service
metadata:
  name: todolistapp-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: todolistapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolistapp
  template:
    metadata:
      labels:
        app: todolistapp
    spec:
      containers:
        - name: todolistapp-container
          image: 074465317714.dkr.ecr.us-east-1.amazonaws.com/test1:latest
          ports:
            - containerPort: 3000
