# service type loadbalancer
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todolistapp
  name: todolistapp-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: todolistapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todolistapp
  name: todolistapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolistapp
  template:
    metadata:
      labels:
        app: todolistapp
    spec:
      containers:
        - name: todolistapp-container
          image: 074465317714.dkr.ecr.us-east-1.amazonaws.com/test1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
